[package]
name = "wasm-hello"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
wasm-bindgen = "0.2.100"

[dependencies.web-sys]
version = "0.3.77"
features = [
    "console",
]
